### ISSUE TITLE
Latex support via mathjax

### ISSUE THREAD

**Issue by mabhijithn** [AlexanderBertrandLab/abertrandlab-website#1]
Enable support for writing equations using latex in all markdown files. Normal solution involves adding mathjax support by adding few lines in the layout files. Can it be done any other way since we are using remote theme? That is, without cloning the theme and changing that?
A test file with latex typesetting has been added in `research.md`.

**Comment by jwouters91** [comment]
how about this? https://github.com/AlexanderBertrandLab/abertrandlab-website/commit/31f294f15d666f9a00f1dc64b8280b10babc1444
